// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bbnApp.Infrastructure.Data;

#nullable disable

namespace bbnApp.Infrastructure.Migrations.ApplicationDbCode
{
    [DbContext(typeof(ApplicationDbCodeContext))]
    partial class ApplicationDbCodeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.AppSettings", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("SettingId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("配置ID");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("默认值");

                    b.Property<sbyte>("IsFiexed")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("固定");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("NowValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("当前值");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<string>("SettingCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("配置代码");

                    b.Property<string>("SettingDesc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("配置说明");

                    b.Property<int>("SettingIndex")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasComment("序号");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("配置名称");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("配置参数类型");

                    b.Property<string>("ValueRange")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasComment("取值范围");

                    b.HasKey("Yhid", "SettingId");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.AppsCode", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("AppId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("应用ID");

                    b.Property<string>("AppCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("应用代码");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("应用名称");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("varchar(100)")
                        .HasComment("角色介绍");

                    b.HasKey("Yhid", "AppId");

                    b.ToTable("AppsCode");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.AreaCode", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("AreaId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnOrder(1)
                        .HasComment("行政区划ID");

                    b.Property<string>("AreaFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("行政区划全称名称");

                    b.Property<sbyte>("AreaLeve")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("行政区划级别");

                    b.Property<string>("AreaLeveName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("行政区划级别名称");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("行政区划名称");

                    b.Property<string>("AreaPId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("行政区划父级ID");

                    b.Property<string>("AreaPoint")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("行政区划所在经纬度");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "AreaId");

                    b.ToTable("AreaCode");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.DataDictionaryCode", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("DicCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("字典代码");

                    b.Property<string>("AppId")
                        .HasColumnType("varchar(40)")
                        .HasComment("应用ID");

                    b.Property<string>("AppName")
                        .HasColumnType("varchar(40)")
                        .HasComment("应用名称");

                    b.Property<int>("DicIndex")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasComment("序号");

                    b.Property<string>("DicName")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasComment("字典名称");

                    b.Property<string>("DicPCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("父级字典代码");

                    b.Property<string>("DicSpell")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasComment("字典简拼");

                    b.Property<sbyte>("IsLeaf")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("叶子节点");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "DicCode");

                    b.ToTable("DataDictionaryCode");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.DataDictionaryList", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("ItemId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("字典ID");

                    b.Property<string>("DicCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("字典代码");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<int>("ItemIndex")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasComment("序号");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("字典项目名称");

                    b.Property<string>("ItemSpell")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("字典项目名称-简拼");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "ItemId");

                    b.ToTable("DataDictionaryList");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.DeviceCode", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("设备ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("设备代码");

                    b.Property<string>("DeviceBarCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("条码号");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("型号");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("设备名称");

                    b.Property<string>("DeviceSpecifications")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("规格");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("设备分类");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LifeUnit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("计量单位");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<int>("ServiceLife")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasComment("使用寿命");

                    b.Property<string>("StorageEnvironment")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("存储环境");

                    b.Property<string>("Usage")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("用途");

                    b.Property<string>("UsageEnvironment")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("使用环境");

                    b.HasKey("Yhid", "DeviceId");

                    b.ToTable("DeviceCode");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.DeviceCommand", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("CommandId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("指令ID");

                    b.Property<string>("ApplicationCP")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("应用通信协议");

                    b.Property<bool>("CRC")
                        .HasColumnType("tinyint(1)")
                        .HasComment("校验码");

                    b.Property<string>("CommandCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("命令代码");

                    b.Property<string>("CommandDescription")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("命令参数说明");

                    b.Property<string>("CommandInfo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("手动构造命令");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("命令名称");

                    b.Property<string>("DeviceAddr")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("设备地址");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("设备ID");

                    b.Property<string>("FunctionCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("功能码");

                    b.Property<string>("HardwareCP")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("硬件通信协议");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<string>("RegCount")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("寄存器数量");

                    b.Property<string>("StartAddr")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("起始地址,大小端");

                    b.HasKey("Yhid", "CommandId");

                    b.ToTable("DeviceCommand");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.DeviceStruct", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("StructId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("构成ID");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("设备ID");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("物资ID");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("物资名称");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("计量单位");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<int>("UtilizeQuantity")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasComment("使用数量");

                    b.HasKey("Yhid", "StructId");

                    b.ToTable("DeviceStruct");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.MaterialsCode", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("MaterialId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("物资ID");

                    b.Property<string>("DangerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("危险分类");

                    b.Property<byte>("IsDanger")
                        .HasMaxLength(1)
                        .HasColumnType("bool")
                        .HasComment("危险物");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("MaterialBarCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("物资条码");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("物资代码");

                    b.Property<string>("MaterialForm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("物资形态");

                    b.Property<int>("MaterialIndex")
                        .HasMaxLength(3)
                        .HasColumnType("int")
                        .HasComment("序号");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("物资名称");

                    b.Property<string>("MaterialSupplies")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("物资材质");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(20)")
                        .HasComment("物资类型");

                    b.Property<string>("OtherParames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("其他参数");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasComment("规格");

                    b.Property<string>("StorageEnvironment")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("存储环境");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("计量单位");

                    b.HasKey("Yhid", "MaterialId");

                    b.ToTable("MaterialsCode");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.ObjectOperationTypes", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("ObjCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("操作对象代码");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(2)
                        .HasComment("权限代码代码");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.HasKey("Yhid", "ObjCode", "PermissionCode");

                    b.ToTable("ObjectOperationTypes");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.OperationObjectsCode", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("ObjCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("操作对象代码");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("所属应用");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ObjDescription")
                        .HasColumnType("varchar(100)")
                        .HasComment("操作对象说明");

                    b.Property<string>("ObjName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("操作对象名称");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "ObjCode");

                    b.ToTable("OperationObjectsCode");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.PermissionsCode", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("PermissionId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("权限代码ID");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("权限代码代码");

                    b.Property<string>("PermissionDescription")
                        .HasColumnType("varchar(100)")
                        .HasComment("权限代码说明");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("权限代码名称");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "PermissionId");

                    b.ToTable("PermissionsCode");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.ResponseAnalysis", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("int")
                        .HasColumnOrder(1)
                        .HasComment("请求id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<string>("RequestHost")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasComment("请求地址");

                    b.Property<string>("RequestIp")
                        .HasColumnType("varchar(40)")
                        .HasComment("请求IP");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasComment("请求路径");

                    b.Property<string>("RequestPeer")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasComment("请求端口");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime")
                        .HasComment("请求时间");

                    b.Property<short>("ResponseTime")
                        .HasColumnType("smallint")
                        .HasComment("响应时间");

                    b.HasKey("ResponseId");

                    b.ToTable("ResponseAnalysis");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.Code.TopicCodes", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("TopicId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("订阅代码ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("订阅代码");

                    b.Property<string>("DeviceIds")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("设备ID,需要指定设备的情况");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("设备分类代码");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("订阅名称");

                    b.Property<string>("TopicRoter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("路由地址");

                    b.Property<string>("TopicType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("订阅分类,设备/基站等");

                    b.HasKey("Yhid", "TopicId");

                    b.ToTable("TopicCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
