// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bbnApp.Infrastructure.Data;

#nullable disable

namespace bbnApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250328022551_AddRoleAppsManagementTable")]
    partial class AddRoleAppsManagementTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("bbnApp.Domain.Entities.Safe.LimiteRecord", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("LimiteId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("限制记录ID");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<DateTime>("LimiteExpireTime")
                        .HasColumnType("datetime")
                        .HasComment("限制有效期,到期自动解除");

                    b.Property<string>("LimiteIP")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasComment("限制IP地址");

                    b.Property<string>("LimiteReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("限制原因");

                    b.Property<DateTime>("LimiteTime")
                        .HasColumnType("datetime")
                        .HasComment("限制记录时间");

                    b.HasKey("Yhid", "LimiteId");

                    b.ToTable("LimiteRecord");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.User.CompanyInfo", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("机构ID");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("所在地行政区划代码");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("所在地行政区划名称");

                    b.Property<string>("AreaNameExt")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("所在地详细信息");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构代码");

                    b.Property<sbyte>("CompanyLeve")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("机构级别,1/2/3/4/5");

                    b.Property<string>("CompanyLeveName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构级别名称,1级/2级/3级/4级");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("机构名称");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构类型,个人/个体/企业/集团");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("联系人");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("Location")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("经纬度坐标");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("组织机构代码");

                    b.Property<string>("PCompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("上级机构ID,企业/集团适用");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("联系电话");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "CompanyId");

                    b.ToTable("CompanyInfo");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.User.DepartMents", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("DepartMentId")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnOrder(1)
                        .HasComment("部门ID");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构ID");

                    b.Property<string>("DepartMentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("部门代码");

                    b.Property<string>("DepartMentDescription")
                        .HasColumnType("varchar(100)")
                        .HasComment("部门介绍");

                    b.Property<sbyte>("DepartMentIndex")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("部门序号,排序显示");

                    b.Property<string>("DepartMentLocation")
                        .HasColumnType("varchar(100)")
                        .HasComment("部门位置");

                    b.Property<string>("DepartMentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("部门名称");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("PDepartMentId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("上级部门ID");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "DepartMentId");

                    b.ToTable("DepartMents");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.User.Employees", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("员工ID");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime")
                        .HasComment("出生日期");

                    b.Property<string>("CommunicationAddress")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasComment("员工通信地址");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构ID");

                    b.Property<DateTime>("DateOfEmployment")
                        .HasColumnType("datetime")
                        .HasComment("入职时间");

                    b.Property<string>("DepartMentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("所在部门ID");

                    b.Property<string>("DepartMentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("所在部门名称");

                    b.Property<string>("EmailNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("员工邮箱");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("员工代码");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("员工姓名");

                    b.Property<string>("EmployeeNum")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("员工工号");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasComment("员工性别");

                    b.Property<string>("IDCardNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("员工证件号码");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("PhoneNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("员工联系电话");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("职务名称");

                    b.Property<sbyte>("PositionLeve")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("职务等级");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.User.Operators", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("分配记录ID");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构ID");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("员工ID");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("密码,需加密");

                    b.Property<DateTime?>("PassWordExpTime")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasComment("密码重置时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "OperatorId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.User.PermissionAssignment", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("PermissionId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("分配记录ID");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构ID");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("操作员ID");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("角色ID");

                    b.HasKey("Yhid", "PermissionId");

                    b.ToTable("PermissionAssignment");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.User.RoleAppsManagement", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("RoleId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("角色ID");

                    b.Property<string>("AppId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(2)
                        .HasComment("应用ID");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构ID");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "RoleId", "AppId");

                    b.ToTable("RoleAppsManagement");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.User.RoleManagment", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("RoleId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("角色ID");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构ID");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("角色代码");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("varchar(100)")
                        .HasComment("角色介绍");

                    b.Property<sbyte>("RoleLeve")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("角色级别");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("角色名称");

                    b.HasKey("Yhid", "RoleId");

                    b.ToTable("RoleManagment");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.User.RolePermissionManagement", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("RoleId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("角色ID");

                    b.Property<string>("ObjCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(2)
                        .HasComment("对象代码");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(3)
                        .HasComment("操作代码");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构ID");

                    b.Property<sbyte>("IsLock")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("停用");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LockReason")
                        .HasColumnType("varchar(40)")
                        .HasComment("停用原因");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime")
                        .HasComment("停用时间");

                    b.Property<string>("ReMarks")
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.HasKey("Yhid", "RoleId", "ObjCode", "PermissionCode");

                    b.ToTable("RolePermissionManagement");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.UserLogin.LoginInfo", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("用户身份ID");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构ID,登录成功时记录");

                    b.Property<DateTime>("Exptime")
                        .HasColumnType("datetime")
                        .HasComment("token过期时间");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LoginFrom")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("登录来源，PC/APP/WX/ZFB");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("备注信息");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasComment("token信息");

                    b.HasKey("Yhid", "EmployeeId");

                    b.ToTable("LoginInfo");
                });

            modelBuilder.Entity("bbnApp.Domain.Entities.UserLogin.LoginRecord", b =>
                {
                    b.Property<string>("Yhid")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(0)
                        .HasComment("用户组ID");

                    b.Property<string>("LoginId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnOrder(1)
                        .HasComment("登录ID");

                    b.Property<string>("AreaInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("登录地区");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("机构ID,登录成功时记录");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasComment("登录用户身份id");

                    b.Property<DateTime>("Exptime")
                        .HasColumnType("datetime")
                        .HasComment("token过期时间");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasComment("登录IP");

                    b.Property<sbyte>("Isdelete")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint")
                        .HasComment("删除标志");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime")
                        .HasComment("末次数据变更时间");

                    b.Property<string>("LoginFrom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("登录来源，PC/APP/WX/ZFB");

                    b.Property<string>("LoginState")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasComment("登录状态,成功/失败");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime")
                        .HasComment("登录时间");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("token信息,成功登录才需要");

                    b.HasKey("Yhid", "LoginId");

                    b.ToTable("LoginRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
